# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PP-PROD scripts documentation
email: asso@pp-prod.org
description: >- # this means to ignore newlines until "baseurl:"
  The purpose of the PPProd non profit association is the development of software applications,
  with the right of use to members.
  The associated activities, carried out by and for members,
  allow the development of software applications,
  with purpose confidentiality/anonymization and finance/crypto trading.
baseurl: "/scripts/" # the subpath of your site, e.g. /blog
url: "https://pp-prod.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: pp-prod.github.io
twitter_username: __ppprod__
github_username:  pp-prod

# Build settings
theme: leap-day
#remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-feed
#  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
